# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aetherflow < Formula
  desc "Async runtime for AI agent work scheduling"
  homepage "https://github.com/baiirun/aetherflow"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.2.0/aetherflow_0.2.0_darwin_amd64.tar.gz"
      sha256 "1fa99e16eaefba8d02d52cfddcc744a841a3ae8753d2a615de036fa6f3785383"

      def install
        bin.install "af"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.2.0/aetherflow_0.2.0_darwin_arm64.tar.gz"
      sha256 "1064e787635e148d5ae7277c5711d41a04f43129fe1b196b9b6e2127fff6c6b7"

      def install
        bin.install "af"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.2.0/aetherflow_0.2.0_linux_amd64.tar.gz"
      sha256 "07d16b39666b4aa040f626a6edb60be22da37eb5a25c383d0939081418c952bb"
      def install
        bin.install "af"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.2.0/aetherflow_0.2.0_linux_arm64.tar.gz"
      sha256 "46030b15c26e989e48e6ebf3634c7bce03df1718445af30c60bba95a2580eed3"
      def install
        bin.install "af"
      end
    end
  end
end
