# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aetherflow < Formula
  desc "Async runtime for AI agent work scheduling"
  homepage "https://github.com/baiirun/aetherflow"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.1.0/aetherflow_0.1.0_darwin_amd64.tar.gz"
      sha256 "5c2d0cd4fdb4c0ae73b1fca72322694ba22fe44456a85bc2f44532cfbc087ea1"

      def install
        bin.install "af"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.1.0/aetherflow_0.1.0_darwin_arm64.tar.gz"
      sha256 "1d472fa07d326c5c23bf9fff628c37fe7a84107aab3a02dc404096ff16e34ab9"

      def install
        bin.install "af"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.1.0/aetherflow_0.1.0_linux_amd64.tar.gz"
      sha256 "08398ead4f942217cea3599c36af23f4a26f5fe240eda7a374440547deb82a77"
      def install
        bin.install "af"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/aetherflow/releases/download/v0.1.0/aetherflow_0.1.0_linux_arm64.tar.gz"
      sha256 "76deb0437947d829ca392a5b82a905ca33702165afe7a0650317e0b996537f14"
      def install
        bin.install "af"
      end
    end
  end
end
