# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prog < Formula
  desc "Cross-session task management CLI for AI agents"
  homepage "https://github.com/baiirun/prog"
  version "0.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/baiirun/prog/releases/download/v0.12.1/prog_0.12.1_darwin_amd64.tar.gz"
      sha256 "821098c2d7cb3b745d705aad8379ac6748c683804aaea39547afb1607f2b500f"

      def install
        bin.install "prog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/baiirun/prog/releases/download/v0.12.1/prog_0.12.1_darwin_arm64.tar.gz"
      sha256 "b289354775f78ca8e225cd0268de97d54b676c34c9c0e61f48328164fd0d93bd"

      def install
        bin.install "prog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/prog/releases/download/v0.12.1/prog_0.12.1_linux_amd64.tar.gz"
      sha256 "f632dadcb39df34c83e248891a90ffb1a800ec517802187461643d9395560668"
      def install
        bin.install "prog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/prog/releases/download/v0.12.1/prog_0.12.1_linux_arm64.tar.gz"
      sha256 "147b2e3ffec34eccc8e4424ebf6d439287d49f8e25e8e957221d487eae92dfce"
      def install
        bin.install "prog"
      end
    end
  end
end
