# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "Cross-session task management CLI for AI agents"
  homepage "https://github.com/baiirun/dotworld-tasks"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.2.0/dotworld-tasks_0.2.0_darwin_amd64.tar.gz"
      sha256 "6dba915acc86f0bebde10789663f89d4819c401ab6c17c7ea4930603bf0d95f8"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.2.0/dotworld-tasks_0.2.0_darwin_arm64.tar.gz"
      sha256 "bfb1cdf8bc8aa1190a09b6ccc47f7334d93d08beed58fca6109227f85ac14f61"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.2.0/dotworld-tasks_0.2.0_linux_amd64.tar.gz"
      sha256 "14965b8df93728d2591954db8d0a6fdd4350fd9f686b8a70a36d11730f49438a"
      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.2.0/dotworld-tasks_0.2.0_linux_arm64.tar.gz"
      sha256 "716b59560817d2f5e65715cd76944bd4872acfdf9d46df363a286195fcffcc4d"
      def install
        bin.install "tasks"
      end
    end
  end
end
