# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "Cross-session task management CLI for AI agents"
  homepage "https://github.com/baiirun/dotworld-tasks"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.3.0/dotworld-tasks_0.3.0_darwin_amd64.tar.gz"
      sha256 "62af44e5ce403792a2dcf1dbdde1f27da672d2f39e574223faf9903083f62b36"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.3.0/dotworld-tasks_0.3.0_darwin_arm64.tar.gz"
      sha256 "b798d074d59c694282e607ec97dd8c356a5adbe41a9529ca592e1ec950741a63"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.3.0/dotworld-tasks_0.3.0_linux_amd64.tar.gz"
      sha256 "6be3cb93e061393a880e0629d3a350c43e4ede5ef813c3ac549295099844456e"
      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/baiirun/dotworld-tasks/releases/download/v0.3.0/dotworld-tasks_0.3.0_linux_arm64.tar.gz"
      sha256 "b9330636937d30534d301f33b4e2abeb5f27c2388220c8bd259af6e310f3dbcc"
      def install
        bin.install "tasks"
      end
    end
  end
end
